# Generated by Django 4.0.2 on 2022-02-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='product_images')),
                ('productname', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=100)),
                ('finalprice', models.CharField(max_length=100)),
                ('previousprice', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
