# Generated by Django 4.0.2 on 2022-02-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exclusive', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
